"use client";

import { useMemo, useState } from "react";
import type { InvestorConstitution } from "@/features/capital/domain/investor-constitution-schema";
import { buildInvestorConstitutionFromIntake, type InvestorConstitutionIntakeAnswers } from "@/features/capital/domain/investor-constitution-intake";
import {
  COMPLEXITY_ALLOWED_LABELS,
  CURRENCY_LABELS,
  EMERGENCY_RESERVE_LABELS,
  FINANCIAL_KNOWLEDGE_LABELS,
  INTAKE_QUESTIONS,
  LIQUIDITY_REQUIREMENT_LABELS,
  OBJECTIVE_LABELS,
  PROHIBITED_INSTRUMENT_LABELS,
  RESULT_TITLE,
  RISK_LEVEL_LABELS,
  TIME_HORIZON_LABELS,
} from "@/lib/capital/investor-constitution-intake-content";

type PartialAnswers = Partial<InvestorConstitutionIntakeAnswers>;

function fieldsetClass() {
  return "flex flex-col gap-2 text-sm text-slate-300";
}

function SummaryRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between border-b border-white/5 py-2 last:border-b-0">
      <span className="text-slate-400">{label}</span>
      <span className="font-medium text-white">{value}</span>
    </div>
  );
}

export function InvestorConstitutionIntakeForm() {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<PartialAnswers>({});
  const [constitution, setConstitution] = useState<InvestorConstitution | null>(null);
  const [saved, setSaved] = useState(false);

  const totalSteps = INTAKE_QUESTIONS.length;
  const question = INTAKE_QUESTIONS[step];
  const isLastStep = step === totalSteps - 1;
  const isAnswerComplete = useMemo(() => INTAKE_QUESTIONS.every((q) => answers[q.field] !== undefined), [answers]);

  const setAnswer = (field: keyof InvestorConstitutionIntakeAnswers, value: string) => {
    setAnswers((prev) => ({ ...prev, [field]: value }));
  };

  const generateConstitution = () => {
    if (!isAnswerComplete) return;
    setConstitution(buildInvestorConstitutionFromIntake(answers as InvestorConstitutionIntakeAnswers));
  };

  if (constitution) {
    return (
      <div className="space-y-4">
        <div className="rounded-2xl border border-cyan-200/30 bg-cyan-300/[0.06] p-6">
          <h3 className="text-xl font-semibold text-white">{RESULT_TITLE}</h3>
          <p className="mt-2 text-sm text-slate-300">
            This constitution shapes which paper-trading simulations you will be able to see. It reflects the answers you just
            gave, mapped deterministically — nothing here was generated by an AI model.
          </p>
        </div>

        <div className="rounded-2xl border border-white/10 bg-white/5 p-5">
          <SummaryRow label="Objective" value={OBJECTIVE_LABELS[constitution.investorObjective]} />
          <SummaryRow label="Time horizon" value={TIME_HORIZON_LABELS[constitution.timeHorizon]} />
          <SummaryRow label="Liquidity requirement" value={LIQUIDITY_REQUIREMENT_LABELS[constitution.liquidityRequirement]} />
          <SummaryRow label="Emergency reserve" value={EMERGENCY_RESERVE_LABELS[constitution.emergencyReserveMonths]} />
          <SummaryRow label="Risk tolerance" value={RISK_LEVEL_LABELS[constitution.riskTolerance]} />
          <SummaryRow label="Risk capacity" value={RISK_LEVEL_LABELS[constitution.riskCapacity]} />
          <SummaryRow label="Knowledge level" value={FINANCIAL_KNOWLEDGE_LABELS[constitution.financialKnowledge]} />
          <SummaryRow label="Complexity allowed" value={COMPLEXITY_ALLOWED_LABELS[constitution.complexityAllowed]} />
          <SummaryRow label="Base currency" value={CURRENCY_LABELS[constitution.baseCurrency]} />
          <SummaryRow label="Spending currency" value={CURRENCY_LABELS[constitution.spendingCurrency]} />
          <SummaryRow label="Max crypto exposure" value={`${constitution.maxCryptoExposurePct}%`} />
          <SummaryRow
            label="Prohibited instruments"
            value={
              constitution.prohibitedInstruments.length > 0
                ? constitution.prohibitedInstruments.map((i) => PROHIBITED_INSTRUMENT_LABELS[i]).join(", ")
                : "None"
            }
          />
          <SummaryRow label="Paper-only" value="Yes" />
          <SummaryRow label="Requires human review" value={constitution.requiresHumanReview ? "Yes" : "No"} />
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            type="button"
            disabled={saved}
            onClick={() => setSaved(true)}
            className="rounded-full border border-emerald-300/30 bg-emerald-300/[0.1] px-5 py-2.5 text-sm font-medium text-emerald-100 transition hover:bg-emerald-300/[0.2] disabled:opacity-50"
          >
            {saved ? "Saved for this session" : "Save Investor Constitution"}
          </button>
          <button
            type="button"
            onClick={() => {
              setConstitution(null);
              setSaved(false);
              setStep(0);
            }}
            className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-200 transition hover:border-cyan-200/30 hover:text-cyan-100"
          >
            Edit answers
          </button>
          <a
            href="/capital"
            className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-200 transition hover:border-cyan-200/30 hover:text-cyan-100"
          >
            Continue later
          </a>
        </div>
        {saved ? (
          <p className="text-xs text-slate-500">
            Saved for this browser session only — there is no persistence layer for Investor Constitutions yet.
          </p>
        ) : null}
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/10 bg-white/5 p-6">
      <div className="mb-5 flex items-center justify-between">
        <p className="text-xs uppercase tracking-[0.2em] text-slate-400">
          Question {step + 1} of {totalSteps}
        </p>
      </div>

      <fieldset className={fieldsetClass()}>
        <legend className="mb-2 text-base text-white">{question.prompt}</legend>
        {question.options.map((option) => (
          <label key={option.value} className="flex items-center gap-2">
            <input
              type="radio"
              name={question.field}
              checked={answers[question.field] === option.value}
              onChange={() => setAnswer(question.field, option.value)}
            />
            {option.label}
          </label>
        ))}
      </fieldset>

      <div className="mt-6 flex items-center gap-3">
        <button
          type="button"
          disabled={step === 0}
          onClick={() => setStep((s) => Math.max(0, s - 1))}
          className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-200 transition hover:border-cyan-200/30 hover:text-cyan-100 disabled:opacity-40"
        >
          Back
        </button>
        {!isLastStep ? (
          <button
            type="button"
            disabled={answers[question.field] === undefined}
            onClick={() => setStep((s) => Math.min(totalSteps - 1, s + 1))}
            className="rounded-full border border-cyan-200/30 bg-cyan-300/[0.08] px-4 py-2 text-sm text-cyan-100 transition hover:bg-cyan-300/[0.16] disabled:opacity-40"
          >
            Next
          </button>
        ) : (
          <button
            type="button"
            disabled={!isAnswerComplete}
            onClick={generateConstitution}
            className="rounded-full border border-cyan-200/30 bg-cyan-300/[0.08] px-4 py-2 text-sm text-cyan-100 transition hover:bg-cyan-300/[0.16] disabled:opacity-50"
          >
            See my Investor Constitution
          </button>
        )}
      </div>
    </div>
  );
}
